### ISSUE TITLE
Modify script for deployment

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/codeforpoznan.pl_v3#385]
#### Subject of the issue:
As we are getting ready to deploy we need to set up how the changes will be pushed onto production. 

#### To-do list
- [ ] Set up production server - replace v2 with v3
- [ ] Prepare infrastructure to work in release cycles
- [ ] Keep dev. server for testing purposes (all changes in master should be pushed automatically here)

**Comment by arturtamborski** [comment]
heyy that's a lot of PRs : )  I finally finished this issue in latest pr #464
