### ISSUE TITLE
Create search bar for participant component

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/codeforpoznan.pl_v3#56]
#### General description
We should be able to search participants by any kind of data to find other details when needed.

#### Technical description
Ideally, a user should be able to type any kind of data (name, surname, github, slack) in the same field and get the probable result.  Given that this function is relevant both for editing details in `participants` component and displaying details in #103 we could extract it in the separate re-usable component. 

#### Resources
We could use the combobox solution like [this](https://github.com/CodeForPoznan/codeforpoznan.pl_v3/blob/master/frontend/src/components/HacknightsParticipants.vue) but without multiple objects as developed 

#### To-do list
- [ ] Extract search function in separate component
- [ ] Use it in participants component (create/edit form has it at the top) and replace v-select to unify the use
- [ ] Make note to use the same solution in #103

**Comment by OtisRed** [comment]
Waiting for the proposal for general design of the backoffice

**Comment by OtisRed** [comment]
@Marce1ina would you like to take this one next? It's a bit more challanging I guess but it also makes more sense to develop #103 after having this one done

**Comment by Marce1ina** [comment]
@OtisRed I can take this one next.
